name: Action Lint

on:
  workflow_call:

jobs:
  action-lint:
    uses: kupecloud/github-workflows/.github/workflows/action-lint.yaml@6c631aa5e3dc896ff8bf5cf5244df96e219fbe6f # v2.5.2
    with:
      runs-on: kupe-small
