name: Action Lint

on:
  workflow_call:

jobs:
  action-lint:
    uses: kupecloud/github-workflows/.github/workflows/action-lint.yaml@75f2bc349709d9fec6630dbd937301d1a32708e0 # v1.1.0
    with:
      runs-on: kupe-small
