name: "Main"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    uses: ./.github/workflows/go-lint.yaml

  action-lint:
    name: Action Lint
    uses: ./.github/workflows/action-lint.yaml

  unit-tests:
    name: Unit Tests
    needs:
      - go-lint
      - action-lint
    uses: ./.github/workflows/unit-tests.yaml

  gosec:
    name: Go Security
    needs:
      - unit-tests
    uses: ./.github/workflows/gosec.yaml

  e2e-tests:
    name: E2E Tests
    needs:
      - gosec
    uses: ./.github/workflows/e2e-tests.yaml

  release:
    name: Release
    needs:
      - e2e-tests
    uses: kupecloud/github-workflows/.github/workflows/semantic-release.yaml@11b5503fe90f8de8fa6c7ceb32ef693f32524722 # v1.0.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write
    secrets: inherit

  docker:
    name: Docker Build
    needs:
      - release
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      push: true
      version: ${{ needs.release.outputs.new_release_version }}
